package org.valuereporter.helper;


import org.apache.commons.dbutils.QueryRunner;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

/**
 * See http://hsqldb.org/doc/guide/running-chapt.html#rgc_new_db
 * @author <a href="bard.lind@gmail.com">Bard Lind</a>
 */
public class DatabaseHelper {
    private static final Logger log = LoggerFactory.getLogger(DatabaseHelper.class);
    private final QueryRunner queryRunner;

    public DatabaseHelper() {
        queryRunner = new QueryRunner();
    }

    public static Connection connectToHsqldb(String jdbcUrl, String userName, String password) {
        Connection c = null;
        try {
            c = DriverManager.getConnection(
                    jdbcUrl + "ifexists=true", userName, password);

        } catch (SQLException e) {
            log.info("Database is not available {}, user {}", jdbcUrl, userName);
        }
        return c;

    }

    public static boolean isHSQLdbAvailable(String jdbcUrl, String username, String password) {
        boolean isExistingDb = false;
        try {
            Connection c = DriverManager.getConnection(
                    jdbcUrl + "ifexists=true", username, password);
            isExistingDb = true;
        } catch (SQLException e) {
            log.info("Database is not available {}, user {}", jdbcUrl, username);
        }
        return isExistingDb;
    }

    private void createDatabaseTables(Connection connection) {
        //TODO
        log.info("Creating UserPropertyAndRole tables.");
        try {
            queryRunner.update(connection, "CREATE TABLE UserRoles (" +
                    "  ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "  UserID char(36) NOT NULL," +
                    "  AppID varchar(32)," +
                    "  OrganizationId varchar(32)," +
                    "  RoleName varchar(32)," +
                    "  RoleValues varchar(256)" +
                    ")");
        } catch (SQLException e) {
            log.info("Error creating tables", e);
        }
    }

    /*
    private BasicDataSource getDataSource() {
        String jdbcdriver = AppConfig.appConfig.getProperty("roledb.jdbc.driver");
        String jdbcurl = AppConfig.appConfig.getProperty("roledb.jdbc.url");
        String roledbuser = AppConfig.appConfig.getProperty("roledb.jdbc.user");
        String roledbpasswd = AppConfig.appConfig.getProperty("roledb.jdbc.password");

        BasicDataSource dataSource = new BasicDataSource();
        dataSource.setDriverClassName(jdbcdriver);
        dataSource.setUrl(jdbcurl);//"jdbc:hsqldb:file:" + basepath + "hsqldb");
        dataSource.setUsername(roledbuser);
        dataSource.setPassword(roledbpasswd);
        return dataSource;
    }
    */
}
