    CREATE TABLE ObservedKeys(
      id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      prefix varchar(255) NOT NULL,
      methodName varchar(255) NOT NULL,
      CONSTRAINT AK_Prefix_MethodName UNIQUE (prefix, methodName)
    );
    insert into ObservedKeys(prefix, methodName) values ('initial', 'com.valuereporter.test');
 

    create table ObservedInterval (
      id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
      observedKeysId bigint NOT NULL ,
      startTime datetime NOT NULL,
      duration bigint not null,
      count bigint NOT NULL,
      max bigint not null,
      min bigint not null,
      mean decimal not null,
      median decimal not null,
      stdDev decimal not null,
      p95 decimal,
      p98 decimal,
      p99 decimal,
      FOREIGN KEY (observedKeysId) REFERENCES ObservedKeys(id)
    );
    insert into ObservedInterval (observedKeysId, startTime, duration, count, max, mean,min,median, stdDev)
      select o.id, '2014-05-13 12:02:43.296', 15*60*1000, 4, 50, 5.0, 2,0,0
      from ObservedKeys o
      where prefix='initial' and methodName = 'com.valuereporter.test';
